install.packages('devtools')
devtools::install_github("ohdsi/ParallelLogger@v1.2.0")
devtools::install_github("ohdsi/DatabaseConnector@v2.4.4")
devtools::install_github("ohdsi/Cyclops@v2.0.1")
devtools::install_github("ohdsi/FeatureExtraction@v2.2.5", force = TRUE)
devtools::install_github("ohdsi/BigKnn@v0.0.3")
devtools::install_github("ohdsi/PatientLevelPrediction@v3.0.2")
install.packages(c('dplyr','epitools','ggfortify','ggplot2','lcmm','lme4','reshape2','survival'))
install.packages(c('shinydashboard','shinyWidgets','shinydashboardPlus','tidyverse','lmerTest'))
install.packages('openssl')
install.packages('jose')
devtools::install_github('ABMI/RTROD_WINGS',ref='master')